Project README
ProgPrak-Native-App/react-native-app pull request #51
Opened 2022-06-17 20:22 UTC by redstarmy

Created a README for our repo. 

- [x] Description of our project
- [x] Link to latest release
- [x] Explained build and publish process
- [ ] Linked contributors in credits
- [x] Linked license 
- [ ] Linked Style guide

2022-06-18 16:56 UTC, MHajoha requested changes

2022-06-18 16:56 UTC, MHajoha commented on CONTRIBUTING.md
> +5. Open a pull request!
Wir benutzen [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/), nicht [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow). Ist was anderes

2022-06-18 16:56 UTC, MHajoha commented on README.md
> +<img alt="Expo QR" src="https://qr.expo.dev/expo-go?owner=progprak_kopfsachen&slug=kopfsachen&releaseChannel=default" width="200" height="200">
Releases landen aber auf dem release channel `main`

2022-06-20 10:44 UTC, redstarmy commented on CONTRIBUTING.md
> +5. Open a pull request!
Stimmt :) kannst dir ja mal den neuen link anschauen

2022-06-20 10:44 UTC, redstarmy commented on README.md
> +<img alt="Expo QR" src="https://qr.expo.dev/expo-go?owner=progprak_kopfsachen&slug=kopfsachen&releaseChannel=default" width="200" height="200">
ah richtig, ist jetzt korrigiert

2022-06-20 12:24 UTC, Sy-D commented
Noch auf Backendprojekt verweisen :)

2022-06-22 08:43 UTC, MHajoha approved these changes

2022-06-22 08:56 UTC, merged