9 sicherheitsnetz
ProgPrak-Native-App/react-native-app pull request #64
Opened 2022-06-30 18:34 UTC by JonahBalshai

2022-07-03 19:53 UTC, MHajoha requested changes
1. Bitte rebase den Branch auf develop.
2. Dann mach bitte `npm run reformat`. Das führt prettier aus, um den Code korrekt zu formatieren.
3. Dann mach bitte `npm run -- lint --fix`. Das führt ESLint aus, und das `--fix` sagt ihm, dass er banale Fehler direkt fixen soll. Es empfiehlt sich, vorher zu committen, um dann zu schauen, ob ESLint auch wirklich sinnvolle Dinge gemacht hat.
4. Etwaige verbleibende ESLint-Probleme dann bitte manuell fixen. (sollte noch was in Code sein, den du nicht angefasst hast, brauchst du das natürlich nicht zu fixen)
5. Dann erneut pushen, damit reviewed werden kann.

2022-07-06 11:00 UTC, redstarmy commented on components/motivators/Motivator.tsx
> +      <StackNavigator.Screen component={SituationControl} name="SituationControl" />
Wäre es eine Möglichkeit für das Sicherheitsnetz einen eigenen Navigator zu haben? Dann ist der main Motivator Navigator nicht so überfüllt.

2022-07-06 11:03 UTC, redstarmy commented on components/motivators/security_net/SecurityNetItem.tsx
> +          </Pressable>
Hier wäre es gut, sichtbar zu machen, welche Ressource ausgewählt ist. Vielleicht indem die ausgewählte Ressource einen Hintergrund bekommt.

2022-07-06 11:07 UTC, redstarmy commented on components/motivators/security_net/SecurityNetAssistance.tsx
> +          style={styles.textinput}></TextInput>
Hier können auch alle body tags collapsed werden

2022-07-06 11:09 UTC, redstarmy commented on components/motivators/security_net/SecurityNetItemView.tsx
> +  const navigation = useNavigation<NavigationProp<MotivatorRoutes>>();
Hier soll laut ESlint der Name der function großgeschrieben werden, damit er bei der navigation nicht meckert.

2022-07-06 11:12 UTC, redstarmy requested changes
Sieht schonmal echt gut aus. Die Funktionalität scheint komplett da zu sein. Ein paar Sachen sind mir noch aufgefallen:

In meinem iOS Simulator zumindest kann man die Ressourcen leider nicht gut erkennen, da sie die selbe Farbe (Schwarz) wie das Sicherheitsnetz haben. Vielleicht könnte man den Icons einen border o.ä. geben. 

Wenn ein Icon ausgewählt ist und zum nächsten Screen navigiert wird, bekomme ich einen Error. Liegt wohl an der Auswahl des Icons:
```
Non-serializable values were found in the navigation state. Check:

Motivators > SecurityNetItem > params.component.icon.$$typeof (Symbol(react.element))
```

2022-07-06 15:39 UTC, JonahBalshai commented on components/motivators/security_net/SecurityNetItem.tsx
> +          </Pressable>
Ja ich war mir nicht sicher wie man das macht kann mir da vielleicht jemand helfen?

2022-07-06 15:48 UTC, JonahBalshai commented
> Sieht schonmal echt gut aus. Die Funktionalität scheint komplett da zu sein. Ein paar Sachen sind mir noch aufgefallen:
> 
> In meinem iOS Simulator zumindest kann man die Ressourcen leider nicht gut erkennen, da sie die selbe Farbe (Schwarz) wie das Sicherheitsnetz haben. Vielleicht könnte man den Icons einen border o.ä. geben.
> 
> Wenn ein Icon ausgewählt ist und zum nächsten Screen navigiert wird, bekomme ich einen Error. Liegt wohl an der Auswahl des Icons:
> 
> ```
> Non-serializable values were found in the navigation state. Check:
> 
> Motivators > SecurityNetItem > params.component.icon.$$typeof (Symbol(react.element))
> ```

Ich krieg dieselbe Warnung bin mir auch nicht sicher woran das liegt vielleicht kennnt sich da jemand aus?

2022-07-07 10:09 UTC, redstarmy commented on components/motivators/security_net/SecurityNetItem.tsx
> +          </Pressable>
Klar, ich würde den Icons über den state einen background geben welcher je nach Auswahl ein oder ausgeblendet wird.

2022-07-07 15:10 UTC, redstarmy commented
> Ich krieg dieselbe Warnung bin mir auch nicht sicher woran das liegt vielleicht kennnt sich da jemand aus?

Es liegt daran, dass als Teil von `SafetyNetDType` ein Non-serializable value in den params der navigation an `SecurityNetAssistance` mitgegeben wird. Es liegt an dem icon welches ein `JSX.Element` ist. 

Besser wäre es, in der navigation nur den Namen des Icons als `string` zu übergeben. Für was am besten in die params gehört sind die docs ganz gut: https://reactnavigation.org/docs/params/#what-should-be-in-params

2022-07-11 11:47 UTC, merged