Jest für zukünftige Unit-Tests konfiguriert und der CI-Pipeline hinzugefügt
ProgPrak-Native-App/react-native-app pull request #76
Opened 2022-07-05 21:01 UTC by Sy-D

Siehe issue #20

2022-07-09 16:57 UTC, MHajoha requested changes
Coole Sache, hatte ich noch nicht von gehört.
Dann gerne rebasen, damit man es in Action sehen kann :+1:

2022-07-09 16:57 UTC, MHajoha commented on .github/workflows/build-android.yml
> +
Dafür lieber einen Job zu ci-cd.yml hinzufügen und zu den "needs" von publish und release hinzufügen

2022-07-10 20:37 UTC, Sy-D commented on .github/workflows/build-android.yml
> +
Erledigt

2022-07-18 15:32 UTC, MHajoha requested changes

2022-07-18 15:32 UTC, MHajoha commented on .github/workflows/ci-cd.yml
> +        run: npm test:ci
Das wird so nicht funktionieren, es fehlt das gesamte setup. Schau dir mal bitte die anderen Jobs an. Und der Workflow ist für den PR nicht gelaufen. Vielleicht liegt das an den Merge-Konflikten :thinking:

2022-08-13 13:16 UTC, MHajoha approved these changes
Sieht aus als müsstest du noch ein npm install machen und dann die package-lock comittem (package.json und package-lock.json stimmen nicht überein.) Wenn die CI auf diesem Branch erfolgreich durchgelaufen ist, kannst du mMn gerne mergen

2024-08-21 12:21 UTC, closed without merging